"""add status to rental

Revision ID: a83472abc5b1
Revises:
Create Date: 2025-06-27 20:14:34.253728

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a83472abc5b1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rentals",
        sa.Column(
            "status",
            sa.Enum("pending", "cancelled", "ongoing", "finished", name="rentalstatus"),
            nullable=False,
            server_default="pending",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rentals", "status")
    # ### end Alembic commands ###
